version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 1GB

  kibana:
    image: kibana:8.15.1
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"

networks:
  elastic:
    driver: bridge